# Generated by Django 4.0.1 on 2022-01-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'drop_off_location',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('auth0_id', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='LostItemPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('image_id', models.OneToOneField(db_column='image_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
                ('lost_user_id', models.ForeignKey(db_column='lost_user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'lost_item_post',
            },
        ),
        migrations.CreateModel(
            name='FoundItemPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('claimed_user_id', models.ForeignKey(db_column='claimed_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimed_user_id', to='api.user')),
                ('drop_off_location_id', models.ForeignKey(db_column='drop_off_location_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.dropofflocation')),
                ('found_user_id', models.ForeignKey(db_column='found_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='found_user_id', to='api.user')),
                ('image_id', models.OneToOneField(db_column='image_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
            ],
            options={
                'db_table': 'found_item_post',
            },
        ),
    ]
