# Generated by Django 4.0.1 on 2022-01-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DropOffLocation',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phoneNumber', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='LostItemPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('lostLocation', models.CharField(max_length=500, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('imageID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
                ('lostUserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'LostItemPost',
            },
        ),
        migrations.CreateModel(
            name='FoundItemPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('foundLocation', models.CharField(max_length=500, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('claimedUserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimedUserID', to='api.user')),
                ('dropOffLocationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dropofflocation')),
                ('foundUserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='foundUserID', to='api.user')),
                ('imageID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
            ],
            options={
                'db_table': 'FoundItemPost',
            },
        ),
    ]
