# Generated by Django 3.2.11 on 2022-01-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditempost',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='lostitempost',
            name='image_id',
        ),
        migrations.AddField(
            model_name='founditempost',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lostitempost',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(default='Computer Engineering', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='term',
            field=models.CharField(default='4A', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
