# Generated by Django 4.0.1 on 2022-01-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditempost',
            name='categoryID',
            field=models.ForeignKey(db_column='categoryID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category'),
        ),
        migrations.AlterField(
            model_name='founditempost',
            name='claimedUserID',
            field=models.ForeignKey(db_column='claimedUserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claimedUserID', to='api.user'),
        ),
        migrations.AlterField(
            model_name='founditempost',
            name='dropOffLocationID',
            field=models.ForeignKey(db_column='dropOffLocationID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.dropofflocation'),
        ),
        migrations.AlterField(
            model_name='founditempost',
            name='foundUserID',
            field=models.ForeignKey(db_column='foundUserID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='foundUserID', to='api.user'),
        ),
        migrations.AlterField(
            model_name='founditempost',
            name='imageID',
            field=models.OneToOneField(db_column='imageID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image'),
        ),
        migrations.AlterField(
            model_name='lostitempost',
            name='categoryID',
            field=models.ForeignKey(db_column='categoryID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.category'),
        ),
        migrations.AlterField(
            model_name='lostitempost',
            name='imageID',
            field=models.OneToOneField(db_column='imageID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.image'),
        ),
        migrations.AlterField(
            model_name='lostitempost',
            name='lostUserID',
            field=models.ForeignKey(db_column='lostUserID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
