# Generated by Django 4.0.1 on 2022-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropofflocation',
            name='locationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dropofflocation',
            table='drop_off_location',
        ),
    ]
