# Generated by Django 4.0.1 on 2022-01-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dropofflocation_locationid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dropofflocation',
            table='DropOffLocation',
        ),
    ]
