# Generated by Django 3.2.11 on 2022-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220118_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditempost',
            name='is_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lostitempost',
            name='is_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
