# Generated by Django 4.0.1 on 2022-01-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dropofflocation',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='LostItemPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('lostLocation', models.CharField(max_length=500, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('imageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'LostItemPost',
            },
        ),
        migrations.CreateModel(
            name='FoundItemPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('foundLocation', models.CharField(max_length=500, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category')),
                ('dropOffLocationID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dropofflocation')),
                ('imageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'db_table': 'FoundItemPost',
            },
        ),
    ]
