# Generated by Django 3.2.11 on 2022-01-20 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220119_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditempost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lostitempost',
            name='location',
        ),
        migrations.AddField(
            model_name='founditempost',
            name='building_id',
            field=models.ForeignKey(db_column='building_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitempost',
            name='building_id',
            field=models.ForeignKey(db_column='building_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.building'),
            preserve_default=False,
        ),
    ]
