# Generated by Django 3.2.11 on 2022-02-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220130_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('chat_room_id', models.ForeignKey(db_column='chat_room_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.chatroom')),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomUser',
            fields=[
                ('chat_room_id', models.OneToOneField(db_column='chat_room_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.chatroom')),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'chat_room_user',
                'unique_together': {('chat_room_id', 'user_id')},
            },
        ),
    ]
