# Generated by Django 3.2.11 on 2022-02-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatroom_chatroomuser_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroomuser',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
