# Generated by Django 3.2.11 on 2022-02-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220203_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='founditempost',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='lostitempost',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
    ]
