# Generated by Django 3.2.11 on 2022-02-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220203_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
