# Generated by Django 3.2.11 on 2022-03-02 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitempost',
            name='building_id',
            field=models.ForeignKey(db_column='building_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.building'),
        ),
    ]
